# Copy this file to 'config/.secrets.toml' and insert your actual tokens.
# The .secrets.toml file is ignored by default via .gitignore.

[preloader]
api_token = "YOUR_API_TOKEN_HERE"
dump_token = "YOUR_DUMP_TOKEN_HERE"
