# Скопируйте этот файл в .secrets.toml и вставьте ваши реальные токены.
# Файл .secrets.toml по умолчанию включен в .gitignore.

[preloader]
api_token = "YOUR_API_TOKEN_HERE"
dump_token = "YOUR_DUMP_TOKEN_HERE"
