[logging]
# Possible levels: DEBUG, INFO, WARNING, ERROR, CRITICAL, FATAL
level = "INFO"

# Common paths for the entire project
[paths]
# Directory for downloaded archives
download_cache_dir = "data/cache"
# Directory for raw parquet files
raw_data_dir = "data/raw"
# Directory for sorted runs.
sorted_runs_dir = "data/runs"
# Directory for storing generated sst files.
sst_files_dir = "data/sst"
# RocksDB root directory.
rocks_db_dir = "data/rocks"

# Settings for the data_preloader component
[preloader]
# Base URL for the 3xpl.com API
api_base_url = "https://api.3xpl.com"
# The number of concurrent downloads to run
concurrent_downloads = 10
# Default network timeout in seconds for all HTTP requests
timeout = 30

[preloader.downloader]
# The size (in bytes) of chunks for streaming file downloads to disk
chunk_size = 8192

[preloader.hasher]
# The size (in bytes) of chunks for reading a local file when calculating its checksum.
chunk_size = 65536

[preloader.processor]
# The number of rows to read from the TSV file into memory at a time.
chunk_size = 1_000_000
# A list of columns to extract from the source TSV for the final Parquet file.
required_columns = ["address", "transaction", "time"]

# Settings for the bulk_loader component
[bulk_loader]
# The number of threads. Set to 0 to use system default (number of CPU cores).
num_threads = 0
