# Common paths for the entire project
[paths]
# Directory for caching downloaded archives and
# storing the final Parquet files.
raw_data_dir = "data/raw"

# Settings for the data_preloader component
[preloader]
# Base URL for the 3xpl.com API
api_base_url = "https://api.3xpl.com"
