[package]
name = "db-test-model"
version.workspace = true
edition.workspace = true

[lib]
bench = false

[dependencies]
hack.workspace = true
anyhow.workspace = true

num-rational = "0.4.2"
rand = "0.9.0"

csv = "1.3.1"
tar = "0.4.44"
resp = "1.0.3"

[build-dependencies]
scratch = "1.0.8"
